# Default values for elasticsearch-openshift
# This is a YAML-formatted file.

# Namespace configuration
namespace:
  name: ""  # Empty means use current namespace
  create: false

# ElasticSearch cluster configuration
elasticsearch:
  clusterName: elasticsearch
  version: "8.18.3"
  
  # Node sets configuration
  nodeSets:
    count: 1
    storage:
      size: 10Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 1000m

# Service configuration
service:
  type: ClusterIP

# Route configuration (OpenShift specific)
route:
  enabled: false
  host: ""  # If empty, OpenShift will auto-generate
  tls:
    enabled: true
    termination: edge

# PodDisruptionBudget configuration
podDisruptionBudget:
  enabled: true
  minAvailable: 1  # At least 1 pod must be available
  # maxUnavailable: 1  # Alternative: maximum 1 pod can be unavailable

# Operator configuration
operator:
  namespace: openshift-operators-redhat
  channel: stable

# Kibana configuration
kibana:
  enabled: true
  version: "8.18.3"
  replicas: 1
  
  # Resources configuration
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m
  
  # Route configuration (OpenShift specific)
  route:
    enabled: true
    host: ""  # If empty, OpenShift will auto-generate
    tls:
      enabled: true
      termination: edge