# Development values for elasticsearch-openshift
# This is a YAML-formatted file with minimal settings for development/testing.

# Namespace configuration
namespace:
  name: elasticsearch-dev
  create: false

# ElasticSearch cluster configuration
elasticsearch:
  clusterName: dev-cluster
  
  # Index management configuration
  indexManagement:
    enabled: false  # Disable for development
  
  # Node specification
  nodeSpec:
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: ""
  
  # Nodes configuration - Minimal setup for development
  nodes:
    - roles:
        - client
        - data
        - master
      storage:
        size: 5Gi
      nodeCount: 1
  
  # Management configuration
  managementState: Managed
  redundancyPolicy: ZeroRedundancy

# Service configuration
service:
  type: ClusterIP

# Route configuration (OpenShift specific)
route:
  enabled: false  # Disable routes for development

# Operator configuration
operator:
  namespace: openshift-operators-redhat
  channel: stable

# ElasticVue configuration
elasticvue:
  enabled: true
  image:
    repository: cars10/elasticvue
    tag: "1.0.4"
    pullPolicy: IfNotPresent
  replicas: 1  # Single replica for development
  
  # Resources configuration
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m
  
  # Service configuration
  service:
    type: ClusterIP
    port: 8080
  
  # Route configuration (OpenShift specific)
  route:
    enabled: false  # Disable routes for development
  
  # ElasticSearch connection
  elasticsearch:
    uri: ""  # Auto-configured to connect to ES cluster 