# Production values for elasticsearch-openshift
# This is a YAML-formatted file with production-ready settings.

# Namespace configuration
namespace:
  name: elasticsearch-prod
  create: false

# ElasticSearch cluster configuration
elasticsearch:
  clusterName: production-cluster
  
  # Index management configuration
  indexManagement:
    enabled: true
    mappings:
      - aliases:
          - infra
          - logs.infra
        name: infra
        policyRef: infra-policy
      - aliases:
          - audit
          - logs.audit
        name: audit
        policyRef: audit-policy
    policies:
      - phases:
          delete:
            namespaceSpec:
              - minAge: 5h
                namespace: openshift-monitoring
            minAge: 7d
            pruneNamespacesInterval: 24h
          hot:
            actions:
              rollover:
                maxAge: 8h
        name: infra-policy
        pollInterval: 30m
      - phases:
          delete:
            minAge: 30d
          hot:
            actions:
              rollover:
                maxAge: 24h
        name: audit-policy
        pollInterval: 30m
  
  # Node specification
  nodeSpec:
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m
  
  # Nodes configuration - Production setup
  nodes:
    - roles:
        - client
        - data
        - master
      storage:
        size: 100Gi
      nodeCount: 3
  
  # Management configuration
  managementState: Managed
  redundancyPolicy: SingleRedundancy

# Service configuration
service:
  type: ClusterIP

# Route configuration (OpenShift specific)
route:
  enabled: true
  host: "elasticsearch-prod.mycompany.com"  # Custom hostname
  tls:
    enabled: true
    termination: edge

# Operator configuration
operator:
  namespace: openshift-operators-redhat
  channel: stable

# ElasticVue configuration
elasticvue:
  enabled: true
  image:
    repository: cars10/elasticvue
    tag: "1.0.4"
    pullPolicy: IfNotPresent
  replicas: 2  # Multiple replicas for high availability
  
  # Resources configuration
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 512Mi
      cpu: 500m
  
  # Service configuration
  service:
    type: ClusterIP
    port: 8080
  
  # Route configuration (OpenShift specific)
  route:
    enabled: true
    host: "elasticvue-prod.mycompany.com"  # Custom hostname
    tls:
      enabled: true
      termination: edge
  
  # ElasticSearch connection
  elasticsearch:
    uri: ""  # Auto-configured to connect to ES cluster 