# Example values for elasticsearch-openshift
# Use this file as a template for your own custom values.

# Namespace configuration
namespace:
  name: elasticsearch-example
  create: true

# Elasticsearch cluster configuration
elasticsearch:
  clusterName: example-cluster
  version: "8.18.3"
  
  # Node sets configuration
  nodeSets:
    count: 3  # Number of nodes (set to 1 for dev, 3+ for production)
    storage:
      size: 20Gi  # Storage per node
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m

# Service configuration
service:
  type: ClusterIP

# Route configuration (OpenShift specific)
route:
  enabled: true
  # host: "elasticsearch-example.apps.example.com"  # Uncomment to set a custom hostname
  tls:
    enabled: true
    termination: edge

# PodDisruptionBudget configuration
podDisruptionBudget:
  enabled: true
  minAvailable: 2  # For production with multiple nodes

# Operator configuration
operator:
  namespace: openshift-operators-redhat
  channel: stable

# Kibana configuration
kibana:
  enabled: true
  version: "8.18.3"
  replicas: 1
  
  # Resources configuration
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m
  
  # Route configuration (OpenShift specific)
  route:
    enabled: true
    # host: "kibana-example.apps.example.com"  # Uncomment to set a custom hostname
    tls:
      enabled: true
      termination: edge 