{{- if .Values.elasticvue.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elasticsearch-openshift.fullname" . }}-elasticvue
  namespace: {{ include "elasticsearch-openshift.namespace" . }}
  labels:
    {{- include "elasticsearch-openshift.elasticvue.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.elasticvue.replicas }}
  selector:
    matchLabels:
      {{- include "elasticsearch-openshift.elasticvue.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "elasticsearch-openshift.elasticvue.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: elasticvue
        image: "{{ .Values.elasticvue.image.repository }}:{{ .Values.elasticvue.image.tag }}"
        imagePullPolicy: {{ .Values.elasticvue.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: ELASTICSEARCH_URI
          value: {{ include "elasticsearch-openshift.elasticsearch.serviceUrl" . }}
        - name: ELASTICSEARCH_USERNAME
          value: "kubeadmin"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "elasticsearch-openshift.clusterName" . }}-es-elastic-user
              key: elastic
        resources:
          {{- toYaml .Values.elasticvue.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch-openshift.elasticvue.serviceName" . }}
  namespace: {{ include "elasticsearch-openshift.namespace" . }}
  labels:
    {{- include "elasticsearch-openshift.elasticvue.labels" . | nindent 4 }}
spec:
  type: {{ .Values.elasticvue.service.type }}
  ports:
  - port: {{ .Values.elasticvue.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "elasticsearch-openshift.elasticvue.selectorLabels" . | nindent 4 }}
{{- end }} 