apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "elasticsearch-openshift.clusterName" . }}
  namespace: {{ include "elasticsearch-openshift.namespace" . }}
  labels:
    {{- include "elasticsearch-openshift.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.elasticsearch.version | default "8.11.0" }}
  nodeSets:
  - name: default
    count: {{ .Values.elasticsearch.nodeSets.count | default 1 }}
    podTemplate:
      metadata:
        labels:
          app: {{ include "elasticsearch-openshift.clusterName" . }}
          cluster-name: {{ include "elasticsearch-openshift.clusterName" . }}
          node.roles: data
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              cpu: {{ .Values.elasticsearch.nodeSets.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.elasticsearch.nodeSets.resources.requests.memory | default "512Mi" }}
            limits:
              cpu: {{ .Values.elasticsearch.nodeSets.resources.limits.cpu | default "1000m" }}
              memory: {{ .Values.elasticsearch.nodeSets.resources.limits.memory | default "1Gi" }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.elasticsearch.nodeSets.storage.size | default "10Gi" }}
    config:
      node.roles:
      - master
      - data
      node.store.allow_mmap: false 