{{- if .Values.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "elasticsearch-openshift.fullname" . }}-elasticsearch
  namespace: {{ include "elasticsearch-openshift.namespace" . }}
  labels:
    {{- include "elasticsearch-openshift.labels" . | nindent 4 }}
    app.kubernetes.io/component: route
spec:
  to:
    kind: Service
    name: {{ include "elasticsearch-openshift.clusterName" . }}-es-http
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
  {{- end }}
{{- end }}

{{- if and .Values.kibana.enabled .Values.kibana.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "elasticsearch-openshift.fullname" . }}-kibana
  namespace: {{ include "elasticsearch-openshift.namespace" . }}
  labels:
    {{- include "elasticsearch-openshift.kibana.labels" . | nindent 4 }}
    app.kubernetes.io/component: route
spec:
  to:
    kind: Service
    name: {{ include "elasticsearch-openshift.clusterName" . }}-kb-http
    weight: 100
  port:
    targetPort: http
  {{- if .Values.kibana.route.tls.enabled }}
  tls:
    termination: {{ .Values.kibana.route.tls.termination }}
  {{- end }}
{{- end }} 